let state = appState;
let realtimeChannel = null;
const loginPanel = document.getElementById("loginPanel"), adminPanel = document.getElementById("adminPanel"), loginError = document.getElementById("loginError"), passwordInput = document.getElementById("bossPasswordInput"), logoutButton = document.getElementById("logoutButton");
const planDate = document.getElementById("planDate"), liveDate = document.getElementById("liveDate"), summaryDate = document.getElementById("summaryDate");
function currentDates(){ return [planDate.value, liveDate.value, summaryDate.value].filter(Boolean); }
async function initAdmin(){ const d=todayISO(); planDate.value=d; liveDate.value=d; summaryDate.value=d; document.getElementById("bossLoginButton").onclick=login; passwordInput.onkeydown=e=>{if(e.key==='Enter')login();}; logoutButton.onclick=logout; document.querySelectorAll(".tab-button").forEach(b=>b.onclick=()=>showTab(b.dataset.tab)); document.getElementById("addStaffButton").onclick=addStaff; document.getElementById("addTemplateButton").onclick=addTemplate; document.getElementById("addJobButton").onclick=addJob; document.getElementById("exportCsvButton").onclick=exportCsv; [planDate,liveDate,summaryDate].forEach(i=>i.onchange=safeReloadAndRender); try{ await loadAppData(currentDates()); state=appState; if(sessionStorage.getItem('bossLoggedIn')==='true') showAdmin(); }catch(e){ showError(loginPanel,e); } }
async function login(){ const entered=passwordInput.value.trim(), expected=(appState.business?.bossPassword||APP_CONFIG.bossPassword||'').trim(); if(entered===expected){ sessionStorage.setItem('bossLoggedIn','true'); loginError.textContent=''; showAdmin(); } else loginError.textContent='Wrong password.'; }
function logout(){ sessionStorage.removeItem('bossLoggedIn'); passwordInput.value=''; loginPanel.classList.remove('hidden'); adminPanel.classList.add('hidden'); logoutButton.classList.add('hidden'); if(realtimeChannel&&db){db.removeChannel(realtimeChannel); realtimeChannel=null;} }
function showAdmin(){ loginPanel.classList.add('hidden'); adminPanel.classList.remove('hidden'); logoutButton.classList.remove('hidden'); renderAll(); if(!realtimeChannel) realtimeChannel=createRealtimeChannel(currentDates,renderAll); }
function showTab(tab){ document.querySelectorAll('.tab-button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab)); document.querySelectorAll('.tab-panel').forEach(p=>p.classList.toggle('active',p.id===`tab-${tab}`)); renderAll(); }
async function safeReloadAndRender(){ try{ await refreshStateForDates(currentDates()); state=appState; renderAll(); }catch(e){showError('planTable',e);} }
function renderAll(){ state=appState; renderTemplateControls(); renderPlan(); renderLive(); renderSummary(); }
function renderTemplateControls(){ document.getElementById('planStaff').innerHTML=activeStaff(state).map(s=>`<option value="${s.id}">${escapeHtml(s.name)}</option>`).join(''); document.getElementById('jobTemplateList').innerHTML=activeTemplates(state).map(t=>`<option value="${escapeHtml(t.name)}"></option>`).join(''); document.getElementById('staffList').innerHTML=activeStaff(state).map(s=>`<div class="list-item"><input value="${escapeHtml(s.name)}" onchange="renameStaff('${s.id}',this.value)"/><button class="danger-button" onclick="removeStaff('${s.id}')">Remove</button></div>`).join(''); document.getElementById('templateList').innerHTML=activeTemplates(state).map(t=>`<div class="list-item"><input value="${escapeHtml(t.name)}" onchange="renameTemplate('${t.id}',this.value)"/><button class="danger-button" onclick="removeTemplate('${t.id}')">Remove</button></div>`).join(''); }
async function addStaff(){ const i=document.getElementById('newStaffName'), name=i.value.trim(); if(!name)return; try{await addStaffRecord(name); i.value=''; renderAll();}catch(e){showError('staffList',e);} }
async function renameStaff(id,value){ if(value.trim()) {await updateStaffRecord(id,{name:value.trim()}); renderAll();} }
async function removeStaff(id){ await updateStaffRecord(id,{active:false}); renderAll(); }
async function addTemplate(){ const i=document.getElementById('newTemplateName'), name=i.value.trim(); if(!name)return; try{await addTemplateRecord(name); i.value=''; renderAll();}catch(e){showError('templateList',e);} }
async function renameTemplate(id,value){ if(value.trim()) {await updateTemplateRecord(id,{name:value.trim()}); renderAll();} }
async function removeTemplate(id){ await updateTemplateRecord(id,{active:false}); renderAll(); }
async function addJob(){ const staffId=document.getElementById('planStaff').value, jobNumber=document.getElementById('planJobNumber').value||'1', name=document.getElementById('planJobName').value.trim(), instructions=document.getElementById('planInstructions').value.trim(); if(!staffId||!name)return; try{await addJobRecord({date:planDate.value,staffId,jobNumber,name,instructions}); document.getElementById('planJobNumber').value=Number(jobNumber)+1; document.getElementById('planJobName').value=''; document.getElementById('planInstructions').value=''; renderAll();}catch(e){showError('planTable',e);} }
function renderPlan(){ const date=planDate.value; document.getElementById('planTable').innerHTML=activeStaff(state).map(s=>{const js=jobsFor(state,date,s.id); return `<div class="staff-group card"><h3>${escapeHtml(s.name)}</h3>${js.length?js.map(planJobRow).join(''):'<p class="muted">No jobs planned.</p>'}</div>`;}).join(''); }
function planJobRow(j){ return `<div class="job-row ${j.status==='running'?'running':''} ${j.status==='finished'?'finished':''}"><input value="${escapeHtml(j.jobNumber)}" onchange="updateJob('${j.id}','jobNumber',this.value)"/><input value="${escapeHtml(j.name)}" onchange="updateJob('${j.id}','name',this.value)"/><input value="${escapeHtml(j.instructions)}" placeholder="Specific instructions" onchange="updateJob('${j.id}','instructions',this.value)"/><span class="badge">${labelStatus(j.status)}</span><button class="danger-button" onclick="deleteJob('${j.id}')">Delete</button></div>`; }
async function updateJob(id,field,value){ const p={}; p[field]=value; await updateJobRecord(id,p); renderAll(); }
async function deleteJob(id){ await deleteJobRecord(id); renderAll(); }
function renderLive(){ const date=liveDate.value, staff=activeStaff(state), total=state.jobs.filter(j=>j.date===date).length, done=state.jobs.filter(j=>j.date===date&&j.status==='finished').length, inCount=staff.filter(s=>{const sh=getShift(state,date,s.id); return sh?.clockIn&&!sh?.clockOut}).length, br=staff.filter(s=>getShift(state,date,s.id)?.onBreak).length; document.getElementById('liveStats').innerHTML=`<div class="stat-card"><span>Staff clocked in</span><strong>${inCount}/${staff.length}</strong></div><div class="stat-card"><span>On break</span><strong>${br}</strong></div><div class="stat-card"><span>Jobs finished</span><strong>${done}/${total}</strong></div><div class="stat-card"><span>Date</span><strong>${date}</strong></div>`; document.getElementById('liveCards').innerHTML=staff.map(s=>liveStaffCard(s,date)).join(''); }
function liveStaffCard(s,date){ const sh=getShift(state,date,s.id), js=jobsFor(state,date,s.id), cur=activeJob(state,date,s.id), onBreak=sh?.onBreak, status=onBreak?'ON BREAK':cur?cur.name:(sh?.clockIn&&!sh?.clockOut?'CLOCKED IN':'CLOCKED OUT'), cls=onBreak?'status-break':cur?'status-running':(sh?.clockIn&&!sh?.clockOut?'status-idle':'status-out'); return `<div class="staff-live-card"><h3>${escapeHtml(s.name)} <span class="badge ${cls}">${escapeHtml(status)}</span></h3><p>Clock in: ${timeOnly(sh?.clockIn)||'-'} &nbsp; Clock out: ${timeOnly(sh?.clockOut)||'-'} &nbsp; Breaks: ${formatMinutes(breakMinutes(state,date,s.id))}</p><div class="button-row wrap"><button class="primary-button" onclick="bossClockIn('${s.id}')">Clock in</button><button class="secondary-button" onclick="bossClockOut('${s.id}')">Clock out</button><button class="warning-button" onclick="bossStartBreak('${s.id}')">Start break</button><button class="secondary-button" onclick="bossEndBreak('${s.id}')">End break</button></div>${cur?`<div class="current-job"><p class="section-label">Current job</p><h3>${escapeHtml(cur.name)}</h3><p>Started: ${timeOnly(cur.actualStart)} · Elapsed: ${formatMinutes(jobMinutes(cur))}</p><button class="secondary-button" onclick="bossFinishJob('${cur.id}')">Finish current job</button></div>`:''}<div class="stack">${js.length?js.map(liveJobRow).join(''):'<p class="muted">No jobs planned.</p>'}</div></div>`; }
function liveJobRow(j){ return `<div class="job-row ${j.status==='running'?'running':''}"><span>#${escapeHtml(j.jobNumber)}</span><div class="job-title"><strong>${escapeHtml(j.name)}</strong><small>${escapeHtml(j.instructions||'No specific instructions')}</small><small>Notes: ${escapeHtml(j.staffNotes||'-')}</small></div><span>${formatMinutes(jobMinutes(j))}</span><div class="form-row"><input type="time" value="${localTimeInputValue(j.actualStart)}" onchange="overrideTime('${j.id}','actualStart',this.value)"/><input type="time" value="${localTimeInputValue(j.actualEnd)}" onchange="overrideTime('${j.id}','actualEnd',this.value)"/></div><div class="button-row"><button class="primary-button" onclick="bossStartJob('${j.id}')">Start</button><button class="secondary-button" onclick="bossFinishJob('${j.id}')">Finish</button></div></div>`; }
async function bossClockIn(id){await clockInRecord(liveDate.value,id);renderAll()} async function bossClockOut(id){await clockOutRecord(liveDate.value,id);renderAll()} async function bossStartBreak(id){await startBreakRecord(liveDate.value,id);renderAll()} async function bossEndBreak(id){await endBreakRecord(liveDate.value,id);renderAll()} async function bossStartJob(id){await startJobRecord(id);renderAll()} async function bossFinishJob(id){await finishJobRecord(id);renderAll()} async function overrideTime(id,field,value){await overrideJobTimeRecord(id,field,value);renderAll()}
function renderSummary(){ const date=summaryDate.value, rows=state.jobs.filter(j=>j.date===date); if(!rows.length){document.getElementById('summaryTable').innerHTML='<p>No jobs for this date.</p>'; return;} document.getElementById('summaryTable').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Staff</th><th>#</th><th>Job</th><th>Status</th><th>Start</th><th>Finish</th><th>Time</th><th>Notes</th></tr></thead><tbody>${rows.map(j=>`<tr><td>${escapeHtml(staffName(state,j.staffId))}</td><td>${escapeHtml(j.jobNumber)}</td><td>${escapeHtml(j.name)}</td><td>${labelStatus(j.status)}</td><td>${timeOnly(j.actualStart)||'-'}</td><td>${timeOnly(j.actualEnd)||'-'}</td><td>${formatMinutes(jobMinutes(j))}</td><td>${escapeHtml(j.staffNotes||'')}</td></tr>`).join('')}</tbody></table></div>`; }
function exportCsv(){ const blob=new Blob([exportCsvFromState(state)],{type:'text/csv'}), a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download=`wtt-job-tracker-backup-${new Date().toISOString().slice(0,10)}.csv`; a.click(); URL.revokeObjectURL(a.href); }
initAdmin();
