let state=appState, selectedStaffId=localStorage.getItem('wtt-selected-staff')||'', realtimeChannel=null;
const staffDate=document.getElementById('staffDate');
async function initStaff(){ staffDate.value=todayISO(); staffDate.onchange=safeReloadAndRender; document.getElementById('changeStaffButton').onclick=()=>{selectedStaffId='';localStorage.removeItem('wtt-selected-staff');renderStaffSelect();}; document.getElementById('clockInButton').onclick=async()=>{await clockInRecord(staffDate.value,selectedStaffId);renderStaffWork();}; document.getElementById('clockOutButton').onclick=async()=>{await clockOutRecord(staffDate.value,selectedStaffId);renderStaffWork();}; document.getElementById('startBreakButton').onclick=async()=>{await startBreakRecord(staffDate.value,selectedStaffId);renderStaffWork();}; document.getElementById('endBreakButton').onclick=async()=>{await endBreakRecord(staffDate.value,selectedStaffId);renderStaffWork();}; document.getElementById('submitDayButton').onclick=submitDay; try{await loadAppData([staffDate.value]); state=appState; if(selectedStaffId&&state.staff.some(s=>s.id===selectedStaffId&&s.active)) showWork(); else renderStaffSelect(); if(!realtimeChannel) realtimeChannel=createRealtimeChannel(()=>[staffDate.value],async()=>{state=appState; selectedStaffId?renderStaffWork():renderStaffSelect();});}catch(e){showError('staffButtons',e);} }
async function safeReloadAndRender(){ try{await refreshStateForDates([staffDate.value]); state=appState; selectedStaffId?renderStaffWork():renderStaffSelect();}catch(e){showError('staffJobList',e);} }
function renderStaffSelect(){ state=appState; document.getElementById('staffSelectPanel').classList.remove('hidden'); document.getElementById('staffWorkPanel').classList.add('hidden'); document.getElementById('changeStaffButton').classList.add('hidden'); document.getElementById('staffButtons').innerHTML=activeStaff(state).map(s=>`<button class="staff-select-button" onclick="selectStaff('${s.id}')">${escapeHtml(s.name)}</button>`).join(''); }
async function selectStaff(id){ selectedStaffId=id; localStorage.setItem('wtt-selected-staff',id); await refreshStateForDates([staffDate.value]); showWork(); }
function showWork(){ document.getElementById('staffSelectPanel').classList.add('hidden'); document.getElementById('staffWorkPanel').classList.remove('hidden'); document.getElementById('changeStaffButton').classList.remove('hidden'); renderStaffWork(); }
function renderStaffWork(){ state=appState; const staff=state.staff.find(s=>s.id===selectedStaffId); if(!staff)return renderStaffSelect(); const date=staffDate.value, sh=getShift(state,date,selectedStaffId), cur=activeJob(state,date,selectedStaffId), banner=document.getElementById('staffStatusBanner'), onBreak=sh?.onBreak; document.getElementById('selectedStaffName').textContent=staff.name; let text='CLOCKED OUT', cls='status-banner clockedout'; if(onBreak){text='ON BREAK';cls='status-banner break';} else if(cur){text=cur.name.toUpperCase();cls='status-banner running';} else if(sh?.clockIn&&!sh?.clockOut){text='CLOCKED IN';cls='status-banner';} banner.className=cls; banner.textContent=text; const isIn=!!(sh?.clockIn&&!sh?.clockOut); document.getElementById('clockInButton').disabled=isIn; document.getElementById('clockOutButton').disabled=!isIn; document.getElementById('startBreakButton').disabled=!isIn||onBreak; document.getElementById('endBreakButton').disabled=!onBreak; const jobs=jobsFor(state,date,selectedStaffId); document.getElementById('staffJobList').innerHTML=jobs.length?jobs.map(jobCard).join(''):'<div class="card"><p>No jobs planned for this date.</p></div>'; }
function jobCard(j){ const run=j.status==='running', fin=j.status==='finished'; return `<div class="staff-job-card ${run?'running':''} ${fin?'finished':''}"><h3>#${escapeHtml(j.jobNumber)} ${escapeHtml(j.name)} <span class="badge">${labelStatus(j.status)}</span></h3>${j.instructions?`<p><strong>Instructions:</strong> ${escapeHtml(j.instructions)}</p>`:''}<p>Time: ${formatMinutes(jobMinutes(j))} · Start: ${timeOnly(j.actualStart)||'-'} · Finish: ${timeOnly(j.actualEnd)||'-'}</p><div class="button-row wrap"><button class="primary-button" onclick="staffStartJob('${j.id}')" ${fin?'disabled':''}>Start</button><button class="secondary-button" onclick="staffPauseJob('${j.id}')" ${!run?'disabled':''}>Pause</button><button class="secondary-button" onclick="staffFinishJob('${j.id}')" ${fin?'disabled':''}>Finish</button></div><label>Notes<textarea rows="3" onchange="updateStaffNotes('${j.id}',this.value)">${escapeHtml(j.staffNotes||'')}</textarea></label></div>`; }
async function staffStartJob(id){await startJobRecord(id);renderStaffWork()} async function staffPauseJob(id){await pauseJobRecord(id);renderStaffWork()} async function staffFinishJob(id){await finishJobRecord(id);renderStaffWork()} async function updateStaffNotes(id,value){await updateJobRecord(id,{staffNotes:value});renderStaffWork()}
async function submitDay(){ const date=staffDate.value, staff=state.staff.find(s=>s.id===selectedStaffId); if(!staff)return; try{await submitDayRecord(date,selectedStaffId); const subject=encodeURIComponent(`WTT Job Tracker submission - ${staff.name} - ${date}`), body=encodeURIComponent(`Staff: ${staff.name}\nDate: ${date}\n\nDay submitted in WTT Job Tracker.\n\nAutomatic email sending will be added later.`); document.getElementById('submitMessage').textContent='Submitted. Email draft opened for testing.'; window.location.href=`mailto:${APP_CONFIG.notificationEmail}?subject=${subject}&body=${body}`; renderStaffWork();}catch(e){showError('submitMessage',e);} }
initStaff();
