/* Supabase data layer for WTT Job Tracker */
const BUSINESS_SLUG = "warrnambool-trays-trailers";
let db = null;
let appState = { business:null, staff:[], templates:[], jobs:[], shifts:[], breaks:[], segments:[], submissions:[] };

function initDbClient(){
  if(!window.supabase) throw new Error("Supabase library is not loaded. Check the script tag in your HTML files.");
  if(!APP_CONFIG.supabaseUrl || !APP_CONFIG.supabaseAnonKey) throw new Error("Supabase URL/key missing in js/config.js");
  if(!db) db = window.supabase.createClient(APP_CONFIG.supabaseUrl, APP_CONFIG.supabaseAnonKey);
  return db;
}
function todayISO(){ return new Date().toISOString().slice(0,10); }
function nowISO(){ return new Date().toISOString(); }
function escapeHtml(str){ return String(str||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])); }
function timeOnly(iso){ if(!iso) return ""; return new Date(iso).toLocaleTimeString([], {hour:"2-digit", minute:"2-digit"}); }
function localTimeInputValue(iso){ if(!iso) return ""; const d=new Date(iso); return `${String(d.getHours()).padStart(2,"0")}:${String(d.getMinutes()).padStart(2,"0")}`; }
function dateTimeFromLocalTime(date,value){ return value ? new Date(`${date}T${value}:00`).toISOString() : null; }
function minutesBetween(start,end){ if(!start) return 0; return Math.max(0,Math.round(((end?new Date(end):new Date())-new Date(start))/60000)); }
function formatMinutes(total){ total=Math.max(0,Number(total||0)); return `${Math.floor(total/60)}h ${String(total%60).padStart(2,"0")}m`; }
function labelStatus(status){ return ({not_started:"Not started",running:"Running",paused:"Paused",finished:"Finished"})[status] || status || "Not started"; }
function showError(target,error){ console.error(error); const el=typeof target==='string'?document.getElementById(target):target; const msg=error?.message||String(error); if(el) el.innerHTML=`<div class="card error-card"><h3>Something went wrong</h3><p>${escapeHtml(msg)}</p></div>`; else alert(msg); }

function activeStaff(state=appState){ return [...state.staff].filter(s=>s.active).sort((a,b)=>(a.displayOrder-b.displayOrder)||a.name.localeCompare(b.name)); }
function activeTemplates(state=appState){ return [...state.templates].filter(t=>t.active).sort((a,b)=>(a.displayOrder-b.displayOrder)||a.name.localeCompare(b.name)); }
function staffName(state,id){ return state.staff.find(s=>s.id===id)?.name || "Unknown"; }
function jobsFor(state,date,staffId=null){ return state.jobs.filter(j=>j.date===date && (!staffId||j.staffId===staffId)).sort((a,b)=>Number(a.jobNumber)-Number(b.jobNumber)); }
function getShift(state,date,staffId){ return state.shifts.find(s=>s.date===date && s.staffId===staffId); }
function activeJob(state,date,staffId){ return state.jobs.find(j=>j.date===date && j.staffId===staffId && j.status==='running'); }
function jobMinutes(job){ return (job.segments||[]).reduce((sum,seg)=>sum+minutesBetween(seg.startedAt,seg.endedAt),0); }
function breakMinutes(state,date,staffId){ let total=state.breaks.filter(b=>b.date===date&&b.staffId===staffId).reduce((s,b)=>s+minutesBetween(b.startedAt,b.endedAt),0); const sh=getShift(state,date,staffId); if(sh?.onBreak&&sh.breakStartedAt) total+=minutesBetween(sh.breakStartedAt,""); return total; }

function normJob(r){ return {id:r.id,businessId:r.business_id,date:r.work_date,staffId:r.staff_id,jobNumber:r.job_number,name:r.name,instructions:r.specific_instructions||"",staffNotes:r.staff_notes||"",status:r.status||"not_started",actualStart:r.actual_start||"",actualEnd:r.actual_end||"",submittedAt:r.submitted_at||"",segments:[]}; }
function normShift(r){ return {id:r.id,businessId:r.business_id,date:r.work_date,staffId:r.staff_id,clockIn:r.clock_in||"",clockOut:r.clock_out||"",onBreak:!!r.on_break,breakStartedAt:r.break_started_at||"",submittedAt:r.submitted_at||""}; }

async function requireBusiness(){ const c=initDbClient(); const {data,error}=await c.from('businesses').select('*').eq('slug',BUSINESS_SLUG).eq('active',true).single(); if(error) throw error; appState.business={id:data.id,name:data.name,slug:data.slug,bossPassword:data.boss_password,notificationEmail:data.notification_email,logoPath:data.logo_path}; return appState.business; }
async function loadReferenceData(){ const c=initDbClient(), b=appState.business||await requireBusiness(); const [sr,tr]=await Promise.all([c.from('staff').select('*').eq('business_id',b.id).eq('active',true).order('display_order').order('name'), c.from('job_templates').select('*').eq('business_id',b.id).eq('active',true).order('display_order').order('name')]); if(sr.error) throw sr.error; if(tr.error) throw tr.error; appState.staff=sr.data.map(r=>({id:r.id,businessId:r.business_id,name:r.name,displayOrder:r.display_order,active:r.active})); appState.templates=tr.data.map(r=>({id:r.id,businessId:r.business_id,name:r.name,displayOrder:r.display_order,active:r.active})); }
async function loadDayData(date){ const c=initDbClient(), b=appState.business||await requireBusiness(); const [jr,sr,br,subr]=await Promise.all([c.from('planned_jobs').select('*').eq('business_id',b.id).eq('work_date',date).order('job_number'), c.from('shifts').select('*').eq('business_id',b.id).eq('work_date',date), c.from('breaks').select('*').eq('business_id',b.id).eq('work_date',date), c.from('submissions').select('*').eq('business_id',b.id).eq('work_date',date)]); for(const r of [jr,sr,br,subr]) if(r.error) throw r.error; const jobs=jr.data.map(normJob); const ids=jobs.map(j=>j.id); let segs=[]; if(ids.length){ const segr=await c.from('job_time_segments').select('*').in('planned_job_id',ids).order('started_at'); if(segr.error) throw segr.error; segs=segr.data.map(r=>({id:r.id,businessId:r.business_id,plannedJobId:r.planned_job_id,startedAt:r.started_at,endedAt:r.ended_at||""})); } jobs.forEach(j=>j.segments=segs.filter(s=>s.plannedJobId===j.id)); appState.jobs=[...appState.jobs.filter(j=>j.date!==date),...jobs]; appState.shifts=[...appState.shifts.filter(s=>s.date!==date),...sr.data.map(normShift)]; appState.breaks=[...appState.breaks.filter(b=>b.date!==date),...br.data.map(r=>({id:r.id,businessId:r.business_id,date:r.work_date,staffId:r.staff_id,startedAt:r.started_at,endedAt:r.ended_at||""}))]; appState.submissions=[...appState.submissions.filter(s=>s.date!==date),...subr.data.map(r=>({id:r.id,businessId:r.business_id,date:r.work_date,staffId:r.staff_id,submittedAt:r.submitted_at}))]; appState.segments=[...appState.segments.filter(s=>!ids.includes(s.plannedJobId)),...segs]; }
async function loadAppData(dates=[todayISO()]){ await requireBusiness(); await loadReferenceData(); for(const d of [...new Set(dates.filter(Boolean))]) await loadDayData(d); return appState; }
async function refreshStateForDates(dates){ return loadAppData(dates); }

async function addStaffRecord(name){ const c=initDbClient(), b=appState.business||await requireBusiness(); const max=appState.staff.reduce((m,s)=>Math.max(m,s.displayOrder||0),0); const {error}=await c.from('staff').insert({business_id:b.id,name,display_order:max+1,active:true}); if(error) throw error; await loadReferenceData(); }
async function updateStaffRecord(id,updates){ const c=initDbClient(); const p={}; if('name'in updates)p.name=updates.name; if('active'in updates)p.active=updates.active; if('displayOrder'in updates)p.display_order=updates.displayOrder; const {error}=await c.from('staff').update(p).eq('id',id); if(error) throw error; await loadReferenceData(); }
async function addTemplateRecord(name){ const c=initDbClient(), b=appState.business||await requireBusiness(); const max=appState.templates.reduce((m,t)=>Math.max(m,t.displayOrder||0),0); const {error}=await c.from('job_templates').insert({business_id:b.id,name,display_order:max+1,active:true}); if(error) throw error; await loadReferenceData(); }
async function updateTemplateRecord(id,updates){ const c=initDbClient(); const p={}; if('name'in updates)p.name=updates.name; if('active'in updates)p.active=updates.active; if('displayOrder'in updates)p.display_order=updates.displayOrder; const {error}=await c.from('job_templates').update(p).eq('id',id); if(error) throw error; await loadReferenceData(); }
async function addJobRecord({date,staffId,jobNumber,name,instructions}){ const c=initDbClient(), b=appState.business||await requireBusiness(); const {error}=await c.from('planned_jobs').insert({business_id:b.id,work_date:date,staff_id:staffId,job_number:Number(jobNumber||1),name,specific_instructions:instructions||'',status:'not_started'}); if(error) throw error; await loadDayData(date); }
async function updateJobRecord(id,updates){ const c=initDbClient(); const job=appState.jobs.find(j=>j.id===id); if(!job)return; const p={updated_at:nowISO()}; if('jobNumber'in updates)p.job_number=Number(updates.jobNumber||1); if('name'in updates)p.name=updates.name; if('instructions'in updates)p.specific_instructions=updates.instructions; if('staffNotes'in updates)p.staff_notes=updates.staffNotes; if('status'in updates)p.status=updates.status; if('actualStart'in updates)p.actual_start=updates.actualStart||null; if('actualEnd'in updates)p.actual_end=updates.actualEnd||null; if('submittedAt'in updates)p.submitted_at=updates.submittedAt||null; const {error}=await c.from('planned_jobs').update(p).eq('id',id); if(error) throw error; await loadDayData(job.date); }
async function deleteJobRecord(id){ const c=initDbClient(); const job=appState.jobs.find(j=>j.id===id); const {error}=await c.from('planned_jobs').delete().eq('id',id); if(error) throw error; if(job) await loadDayData(job.date); }
async function ensureShiftRecord(date,staffId){ const c=initDbClient(), b=appState.business||await requireBusiness(); let sh=getShift(appState,date,staffId); if(sh)return sh; const {data,error}=await c.from('shifts').insert({business_id:b.id,work_date:date,staff_id:staffId}).select('*').single(); if(error) throw error; sh=normShift(data); appState.shifts.push(sh); return sh; }
async function updateShiftRecord(date,staffId,updates){ const c=initDbClient(), b=appState.business||await requireBusiness(); await ensureShiftRecord(date,staffId); const p={updated_at:nowISO()}; if('clockIn'in updates)p.clock_in=updates.clockIn||null; if('clockOut'in updates)p.clock_out=updates.clockOut||null; if('onBreak'in updates)p.on_break=!!updates.onBreak; if('breakStartedAt'in updates)p.break_started_at=updates.breakStartedAt||null; if('submittedAt'in updates)p.submitted_at=updates.submittedAt||null; const {error}=await c.from('shifts').update(p).eq('business_id',b.id).eq('work_date',date).eq('staff_id',staffId); if(error) throw error; await loadDayData(date); }
async function clockInRecord(date,staffId){ const sh=await ensureShiftRecord(date,staffId); if(!sh.clockIn) await updateShiftRecord(date,staffId,{clockIn:nowISO(),clockOut:'',submittedAt:''}); else if(sh.clockOut) await updateShiftRecord(date,staffId,{clockOut:'',submittedAt:''}); }
async function clockOutRecord(date,staffId){ const sh=await ensureShiftRecord(date,staffId); if(sh.onBreak) await endBreakRecord(date,staffId); const run=activeJob(appState,date,staffId); if(run) await pauseJobRecord(run.id); await updateShiftRecord(date,staffId,{clockOut:nowISO()}); }
async function startBreakRecord(date,staffId){ const sh=await ensureShiftRecord(date,staffId); if(!sh.clockIn) await clockInRecord(date,staffId); const run=activeJob(appState,date,staffId); if(run) await pauseJobRecord(run.id); await updateShiftRecord(date,staffId,{onBreak:true,breakStartedAt:nowISO()}); }
async function endBreakRecord(date,staffId){ const c=initDbClient(), b=appState.business||await requireBusiness(); const sh=getShift(appState,date,staffId); if(!sh?.onBreak||!sh.breakStartedAt)return; const {error}=await c.from('breaks').insert({business_id:b.id,work_date:date,staff_id:staffId,started_at:sh.breakStartedAt,ended_at:nowISO()}); if(error) throw error; await updateShiftRecord(date,staffId,{onBreak:false,breakStartedAt:''}); }
async function startJobRecord(jobId){ const c=initDbClient(), b=appState.business||await requireBusiness(); const job=appState.jobs.find(j=>j.id===jobId); if(!job)return; await clockInRecord(job.date,job.staffId); const sh=getShift(appState,job.date,job.staffId); if(sh?.onBreak) await endBreakRecord(job.date,job.staffId); const run=activeJob(appState,job.date,job.staffId); if(run&&run.id!==job.id) await pauseJobRecord(run.id); const start=nowISO(); const p={status:'running',actual_end:null,updated_at:nowISO()}; if(!job.actualStart)p.actual_start=start; let r=await c.from('planned_jobs').update(p).eq('id',job.id); if(r.error)throw r.error; r=await c.from('job_time_segments').insert({business_id:b.id,planned_job_id:job.id,started_at:start}); if(r.error)throw r.error; await loadDayData(job.date); }
async function pauseJobRecord(jobId){ const c=initDbClient(); const job=appState.jobs.find(j=>j.id===jobId); if(!job||job.status!=='running')return; const seg=job.segments.find(s=>!s.endedAt); if(seg){ const r=await c.from('job_time_segments').update({ended_at:nowISO()}).eq('id',seg.id); if(r.error)throw r.error; } const r=await c.from('planned_jobs').update({status:'paused',updated_at:nowISO()}).eq('id',job.id); if(r.error)throw r.error; await loadDayData(job.date); }
async function finishJobRecord(jobId){ const c=initDbClient(); const job=appState.jobs.find(j=>j.id===jobId); if(!job)return; const finish=nowISO(); const seg=job.segments.find(s=>!s.endedAt); if(seg){ const r=await c.from('job_time_segments').update({ended_at:finish}).eq('id',seg.id); if(r.error)throw r.error; } const r=await c.from('planned_jobs').update({status:'finished',actual_start:job.actualStart||finish,actual_end:finish,updated_at:nowISO()}).eq('id',job.id); if(r.error)throw r.error; await loadDayData(job.date); }
async function overrideJobTimeRecord(jobId,field,timeValue){ const job=appState.jobs.find(j=>j.id===jobId); if(!job)return; const value=dateTimeFromLocalTime(job.date,timeValue); if(field==='actualStart') await updateJobRecord(jobId,{actualStart:value}); if(field==='actualEnd') await updateJobRecord(jobId,{actualEnd:value}); }
async function submitDayRecord(date,staffId){ const c=initDbClient(), b=appState.business||await requireBusiness(); const submittedAt=nowISO(); await ensureShiftRecord(date,staffId); await updateShiftRecord(date,staffId,{submittedAt}); for(const j of jobsFor(appState,date,staffId)) await updateJobRecord(j.id,{submittedAt}); const {error}=await c.from('submissions').insert({business_id:b.id,work_date:date,staff_id:staffId,submitted_at:submittedAt}); if(error)throw error; await loadDayData(date); }
function createRealtimeChannel(dates,onChange){ const c=initDbClient(); const businessId=appState.business?.id; if(!businessId)return null; return c.channel(`wtt-${businessId}`).on('postgres_changes',{event:'*',schema:'public'},async()=>{try{await refreshStateForDates(dates()); await onChange();}catch(e){console.error(e);}}).subscribe(); }
function exportCsvFromState(state){ const lines=[["type","date","staff","job_number","job","status","start","finish","minutes","instructions","staff_notes","submitted_at"]]; state.jobs.forEach(j=>lines.push(["job",j.date,staffName(state,j.staffId),j.jobNumber,j.name,j.status,j.actualStart,j.actualEnd,jobMinutes(j),j.instructions||"",j.staffNotes||"",j.submittedAt||""])); state.shifts.forEach(s=>lines.push(["shift",s.date,staffName(state,s.staffId),"","","",s.clockIn,s.clockOut,"","","",s.submittedAt||""])); return lines.map(row=>row.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(',')).join('\n'); }
